const t = @import("traits.zig");

pub const CardType = enum {
    Combat,
    Equipment,
    Event,
    Luck,
    Personnel,

    // only use these for drawing function
    Faction,
    World,
};

pub const Card = struct {
    name: []const u8,
    type: CardType,
    cost: c_int,
    traits: []const []const u8,
    text: []const u8,
};

pub const others = .{
    Card{
        .name = "Defending the Crown Jewels",
        .type = .Combat,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Play only when the battleground is worth Prestige.\nStrength +1",
    },
    Card{
        .name = "Form Ranks!",
        .type = .Combat,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Play only if you have a [" ++ t.Military ++ "] Personnel committed to this attack.\nStrength +1",
    },
    Card{
        .name = "Just in Time",
        .type = .Combat,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "You must move and spend a [" ++ t.Ship ++ "] from a different World to the battleground to play this.\nStrength +2",
    },
    Card{
        .name = "Last Stand",
        .type = .Combat,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Discard one of your committed Personnel. You cannot lose pops due to the result of this attack.",
    },
    Card{
        .name = "Not One of Us",
        .type = .Combat,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Remove all Personnel from this attack.",
    },
    Card{
        .name = "Reinforcements",
        .type = .Combat,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Strength +1",
    },
    Card{
        .name = "Tactical Withdrawal",
        .type = .Combat,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "One of your committed Personnel does not take part in this attack.",
    },

    Card{
        .name = "Deep Core Rig",
        .type = .Equipment,
        .cost = 1,
        .traits = &[_][]const u8{t.Machinery},
        .text = "Play only on a World with Size 4 or more.\nAction: Gain 1 Credit.",
    },
    Card{
        .name = "Freighter",
        .type = .Equipment,
        .cost = 2,
        .traits = &[_][]const u8{t.Ship},
        .text = "Action: Reassign this and any number of your Personnel here to another World. You may also move up to 3 pips.",
    },
    Card{
        .name = "Good Ideas Machine",
        .type = .Equipment,
        .cost = 2,
        .traits = &[_][]const u8{t.Machinery},
        .text = "Action (1): Draw a card.",
    },
    Card{
        .name = "Green-Tinged Gigadiamond",
        .type = .Equipment,
        .cost = 3,
        .traits = &[_][]const u8{t.Jewel},
        .text = "The winner of an attack here may steal this.\nPrestige +2",
    },
    Card{
        .name = "Hypertransport Node",
        .type = .Equipment,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Action: Add a pip to a World.",
    },
    Card{
        .name = "Interstellar Cannon",
        .type = .Equipment,
        .cost = 3,
        .traits = &[_][]const u8{ t.InterstellarWeaponry, t.Illegal },
        .text = "World must have a [" ++ t.MilitaryResource ++ "].\nAction (1): Destroy a pop of your choice on a different World.",
    },
    Card{
        .name = "Planetary Shield",
        .type = .Equipment,
        .cost = 2,
        .traits = &[_][]const u8{t.Defence},
        .text = "Other players may not Reassign to or from here.\nIgnore the effects of [" ++ t.InterstellarWeaponry ++ "], [" ++ t.OrbitalWeaponry ++ "] and [" ++ t.SpaceWeather ++ "] here.",
    },
    Card{
        .name = "Sleek Transport",
        .type = .Equipment,
        .cost = 1,
        .traits = &[_][]const u8{t.Ship},
        .text = "Action: Reassign this and one of your Personnel here to another World.",
    },

    Card{
        .name = "Accidental Colony",
        .type = .Event,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "You must discard one of your [" ++ t.Ship ++ "]s to play this.\nPlay a World and add a pop to it.",
    },
    Card{
        .name = "Arrival of the Ark",
        .type = .Event,
        .cost = 2,
        .traits = &[_][]const u8{},
        .text = "You may play a World. Choose a World then add a pop and a pip to it.",
    },
    Card{
        .name = "Long Term Plans",
        .type = .Event,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Draw 3 cards. You cannot Play non-Combat cards this turn.",
    },
    Card{
        .name = "Mass Migration",
        .type = .Event,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Redistribute your pips among any number of Worlds.",
    },
    Card{
        .name = "Mission to Deep Space",
        .type = .Event,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Enters play spent.\nAction: Discard this. Play 2 Worlds.",
    },
    Card{
        .name = "Raiding Party",
        .type = .Event,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Play only if you can still Attack this turn.\nMove one of your Personnel from one World to another World. Begin an attack with at least that Personnel committed.",
    },

    Card{
        .name = "Galactic Council Emergency Meeting",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "Stays in play.\nEach player may choose from Equipment in play. Any Equipment with a matching name is considered to be [" ++ t.Illegal ++ "].",
    },
    Card{
        .name = "Meteor Shower",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{t.SpaceWeather},
        .text = "Each player chooses one of their Equipment. Discard them all.",
    },
    Card{
        .name = "Rare Mineral Discovery",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "You gain 2 Credits.",
    },
    Card{
        .name = "Spacetime Eddies",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{},
        .text = "No Reassignment can occur this turn.",
    },
    Card{
        .name = "Spacing Guild Dispute",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{t.IndustrialAction},
        .text = "Stays in play.\nReassignment gains a Cost of 1.\nAction (3): Discard this. Any player may use this action.",
    },
    Card{
        .name = "Visitations from an Unknown Species",
        .type = .Luck,
        .cost = 0,
        .traits = &[_][]const u8{t.Aliens},
        .text = "You may place 3 pips anywhere. Each other player may place 1 pip anywhere",
    },

    Card{
        .name = "Assassin",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{t.Illegal},
        .text = "Action (X): Discard this and another Personnel with cost X.",
    },
    Card{
        .name = "Commissar",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Action: Discard another one of your Personnel here. You may attack again this turn.",
    },
    Card{
        .name = "Crusader",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{t.Military},
        .text = "Action: Discard an [" ++ t.Illegal ++ "] card here.",
    },
    Card{
        .name = "Drifter",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Ready: Assign this to any World.",
    },
    Card{
        .name = "Railroad Operative",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{t.Illegal},
        .text = "Ready: You may move one of your pips to a different world.",
    },
    Card{
        .name = "Reclusive Farmer",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{},
        .text = "Growth: If this World was not Taxed this turn, add 2 pips.",
    },
    Card{
        .name = "Survivor of a Hundred Battles",
        .type = .Personnel,
        .cost = 1,
        .traits = &[_][]const u8{t.Military},
        .text = "Combat: Strength +1",
    },
    Card{
        .name = "Tax Collector",
        .type = .Personnel,
        .cost = 2,
        .traits = &[_][]const u8{},
        .text = "You gain an additional 1 Credit when this world is Taxed.",
    },
};
